### ISSUE TITLE
systemd-firstboot.service prevents system from booting up

### ISSUE THREAD

**Issue by ZeroAurora** [AOSC-Dev/AOSCOSLauncher#23]
## Update

dbus.socket is actually being blocked by another service `systemd-firstboot`. This service stuck on boot and prevents the system from fully booting up. The following original issue is only for referencing.

<details>

No journals, no warnings or errors. I can't really find out what's wrong.
![图片](https://github.com/AOSC-Dev/AOSCOSLauncher/assets/25359455/daee33bf-d7bf-473d-836b-0b6ba1686584)
I tried to upgrade the system, terminate WSL and "reboot" it but it's of no use. The only way to get it "up and running" *magically* is to start a Debian (or any other distros that can run DBus/systemd) WSL instance by side with DBus running.
![图片](https://github.com/AOSC-Dev/AOSCOSLauncher/assets/25359455/63f63cc6-2805-4a74-95d4-b2c347211e8a)
And the magic persists, even if I do `wsl --shutdown`.
![图片](https://github.com/AOSC-Dev/AOSCOSLauncher/assets/25359455/4c926c2f-fe3a-4176-a04d-59c720c3c43f)

This should be a half upstream problem but I can't determine where is wrong. Posting here for help.
`uname -a`: `Linux ZA-Desktop 5.15.137.3-microsoft-standard-WSL2 #1 SMP Mon Nov 6 23:32:38 UTC 2023 x86_64 GNU/Linux`
`wsl --version`:
```
WSL 版本： 2.1.0.0
内核版本： 5.15.137.3-1
WSLg 版本： 1.0.59
MSRDC 版本： 1.2.4677
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22635.2552
```

</details>

## Cause

`systemd-firstboot.service` sticks on first boot, thus blocking other services from booting up.

I tried to use other distros and they just works, without firstboot sticking.

**Comment by ZeroAurora** [comment]
Append: Comfirmed and reproduced in AOSC QQ Group. Tried downgrading WSL to 2.0.14 and 2.0.9 and still not working.

**Comment by ZeroAurora** [comment]
Noticed that actually the system isn't fully booted up. This is the cause for dbus not starting.
Some dev suggested to disable sshd service, but not working for my env.
I discovered that the boot process stuck at `systemd-firstboot.service` by running `sudo systemctl list-jobs`.
Killed it and works.
Changing the issue title...

<img width="893" alt="936dbfddca4e5200d9d2e06fb4fe08a0" src="https://github.com/AOSC-Dev/AOSCOSLauncher/assets/25359455/6143c683-b929-48ac-87e5-6fc90c905b97">

**Comment by ZeroAurora** [comment]
After discovering with that dev, we finally found the cause: `/etc/machine-id` is mounted RO by WSL.
Last question: why? why not others?

**Comment by ZeroAurora** [comment]
![图片](https://github.com/AOSC-Dev/AOSCOSLauncher/assets/25359455/30920469-bc07-487b-8c6d-88ebea7ef38d)
Transferring this issue to build tree...

**Comment by Fearyncess** [comment]
https://github.com/AOSC-Dev/aoscbootstrap/blob/master/assets/cleanup.sh#L43 this line makes `/etc/machine-id` missing in generated tarball. thus let wsl or the other things hijacked this file, let it become a read-only file.
